# No gradle deamon for CI
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
 - export GRADLE_USER_HOME=`pwd`/java_backend/.gradle

server:build:
  image: gradle:alpine
  stage: build
  script:
    - cd java_backend
    - gradle --build-cache assemble
  cache:
    key: "$CI_PIPELINE_ID-server"
    policy: push
    paths:
      - build
      - .gradle

webui:build:
  image: node:alpine
  stage: test
  script:
    - apk add --update nodejs nodejs-npm openjdk8
    - npm install --save vnu-jar
    - cd web_frontend
    - java -jar $(npm root)/vnu-jar/build/dist/vnu.jar index.html

server:tests:
  image: gradle:alpine
  stage: test
  script:
    - cd java_backend
    - gradle test
  cache:
    key: "$CI_PIPELINE_ID-server"
    policy: pull
    paths:
      - build
      - .gradle

server:QA:
  image: gradle:alpine
  stage: test
  script:
    - cd java_backend
    - gradle check -x test
  cache:
    key: "$CI_PIPELINE_ID-server"
    policy: pull
    paths:
      - buile
      - .gradle

