CREATE TABLE minions (
    `list_cardId` VARCHAR(10) CHARACTER SET utf8,
    `list_dbfId` INT,
    `list_name` VARCHAR(21) CHARACTER SET utf8,
    `list_cardSet` VARCHAR(7) CHARACTER SET utf8,
    `list_type` VARCHAR(6) CHARACTER SET utf8,
    `list_faction` VARCHAR(8) CHARACTER SET utf8,
    `list_rarity` VARCHAR(9) CHARACTER SET utf8,
    `list_cost` INT,
    `list_attack` INT,
    `list_health` INT,
    `list_flavor` VARCHAR(182) CHARACTER SET utf8,
    `list_artist` VARCHAR(22) CHARACTER SET utf8,
    `list_collectible` VARCHAR(4) CHARACTER SET utf8,
    `list_playerClass` VARCHAR(7) CHARACTER SET utf8,
    `list_img` VARCHAR(75) CHARACTER SET utf8,
    `list_imgGold` VARCHAR(89) CHARACTER SET utf8,
    `list_locale` VARCHAR(4) CHARACTER SET utf8,
    `list_text` VARCHAR(88) CHARACTER SET utf8,
    `list_mechanics_name` VARCHAR(13) CHARACTER SET utf8,
    `list_race` VARCHAR(9) CHARACTER SET utf8,
    `list_elite` VARCHAR(4) CHARACTER SET utf8,
    `list_howToGetGold` VARCHAR(29) CHARACTER SET utf8,
    `list_howToGet` VARCHAR(21) CHARACTER SET utf8
);
INSERT INTO minions VALUES ('CS2_231',179,'Wisp','Classic','Minion','Neutral','Common',0,1,1,'If you hit an Eredar Lord with enough Wisps, it will explode. But why?','Malcolm Davis','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_231.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_231_premium.gif','enUS',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_188',242,'Abusive Sergeant','Classic','Minion','Alliance','Common',1,1,1,'ADD ME TO YOUR DECK, MAGGOT!','Luca Zontini','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_188.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_188_premium.gif','enUS','Battlecry: Give a minion +2_Attack this turn.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_009',1688,'Angry Chicken','Classic','Minion',NULL,'Rare',1,1,1,'There is no beast more frightening (or ridiculous) than a fully enraged chicken.','Mike Sass','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_009.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_009_premium.gif','enUS','Has +5 Attack while damaged.',NULL,'Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_008',757,'Argent Squire','Classic','Minion','Alliance','Common',1,1,1,'"I solemnly swear to uphold the Light, purge the world of darkness, and to eat only burritos." - The Argent Dawn Oath','Zoltan & Gabor','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_008.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_008_premium.gif','enUS','Divine Shield','Divine Shield',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_059',469,'Blood Imp','Classic','Minion','Neutral','Common',1,0,1,'Imps are content to hide and viciously taunt everyone nearby.','Bernie Kang','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_059.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_059_premium.gif','enUS','[x] Stealth. At the end of your \nturn, give another random\n friendly minion +1 Health.','Stealth','Demon',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_319',1090,'Flame Imp','Classic','Minion','Neutral','Common',1,3,2,'Imps like being on fire. They just do.','Alex Horley Orlandelli','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_319.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_319_premium.gif','enUS','Battlecry: Deal 3 damage to your hero.','Battlecry','Demon',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_538t',1715,'Hound','Classic','Minion',NULL,NULL,1,1,1,NULL,NULL,NULL,'Hunter','http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_538t.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/EX1_538t_premium.gif','enUS','Charge','Charge','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('NEW1_017',443,'Hungry Crab','Classic','Minion',NULL,'Epic',1,1,2,'Murloc. It''s what''s for dinner.','Jaemin Kim','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/NEW1_017.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/NEW1_017_premium.gif','enUS','Battlecry: Destroy a Murloc and gain +2/+2.','Battlecry','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_029',658,'Leper Gnome','Classic','Minion','Neutral','Common',1,1,1,'He really just wants to be your friend, but the constant rejection is starting to really get to him.','Glenn Rane','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_029.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_029_premium.gif','enUS','Deathrattle: Deal 2 damage to the enemy_hero.','Deathrattle',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_405',866,'Shieldbearer','Classic','Minion','Neutral','Common',1,0,4,'Have you seen the size of the shields in this game?? This is no easy job.','Carl Critchlow','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_405.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_405_premium.gif','enUS','Taunt','Taunt',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_152',482,'Squire','Classic','Minion','Alliance','Common',1,2,2,NULL,NULL,NULL,'Neutral','http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_152.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/CS2_152_premium.gif','enUS',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_010',994,'Worgen Infiltrator','Classic','Minion','Alliance','Common',1,2,1,'If you want to stop a worgen from infiltrating, just yell, "No! Bad boy!"','Raymond Swanland','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_010.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_010_premium.gif','enUS','Stealth','Stealth',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_169',641,'Young Dragonhawk','Classic','Minion','Horde','Common',1,1,1,'They were the inspiration for the championship Taurenball team: The Dragonhawks.','Greg Hildebrandt','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_169.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_169_premium.gif','enUS','Windfury','Windfury','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_004',1634,'Young Priestess','Classic','Minion',NULL,'Rare',1,2,1,'She can''t wait to learn Power Word: Fortitude Rank 2.','Vance Kovacs','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_004.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_004_premium.gif','enUS','At the end of your turn, give another random friendly minion +1 Health.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_393',790,'Amani Berserker','Classic','Minion','Neutral','Common',2,2,3,'If an Amani berserker asks "Joo lookin'' at me?!", the correct response is "Nah, mon".','Chippy','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_393.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_393_premium.gif','enUS','Has +3 Attack while damaged.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_362',1022,'Argent Protector','Classic','Minion','Neutral','Common',2,2,2,'"I''m not saying you can dodge fireballs. I''m saying with this shield, you won''t have to."','Doug Alexander','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_362.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_362_premium.gif','enUS','Battlecry: Give a friendly minion Divine Shield.','Divine Shield',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_362',1022,'Argent Protector','Classic','Minion','Neutral','Common',2,2,2,'"I''m not saying you can dodge fireballs. I''m saying with this shield, you won''t have to."','Doug Alexander','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_362.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_362_premium.gif','enUS','Battlecry: Give a friendly minion Divine Shield.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_012',749,'Bloodmage Thalnos','Classic','Minion','Neutral','Legendary',2,1,1,'He''s in charge of the Annual Scarlet Monastery Blood Drive!','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_012.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_012_premium.gif','enUS','Spell Damage +1\nDeathrattle: Draw a card.','Deathrattle',NULL,'True',NULL,NULL);
INSERT INTO minions VALUES ('EX1_012',749,'Bloodmage Thalnos','Classic','Minion','Neutral','Legendary',2,1,1,'He''s in charge of the Annual Scarlet Monastery Blood Drive!','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_012.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_012_premium.gif','enUS','Spell Damage +1\nDeathrattle: Draw a card.','Spell Damage',NULL,'True',NULL,NULL);
INSERT INTO minions VALUES ('NEW1_018',999,'Bloodsail Raider','Classic','Minion',NULL,'Common',2,2,3,'"I only plunder on days that end in ''y''."','Jim Nelson','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/NEW1_018.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/NEW1_018_premium.gif','enUS','Battlecry: Gain Attack equal to the Attack\nof your weapon.','Battlecry','Pirate',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_059',801,'Crazed Alchemist','Classic','Minion','Neutral','Rare',2,2,2,'"You''ll love my new recipe!" he says... especially if you''re not happy with your current number of limbs.','Tom Fleming','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_059.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_059_premium.gif','enUS','Battlecry: Swap the Attack and Health of a minion.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_603',285,'Cruel Taskmaster','Classic','Minion','Neutral','Common',2,2,2,'"I''m going to need you to come in on Sunday." - Cruel Taskmaster','Phroilan Gardner','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_603.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_603_premium.gif','enUS','Battlecry: Deal 1 damage to a minion and give it +2_Attack.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_162',985,'Dire Wolf Alpha','Classic','Minion','Neutral','Common',2,2,2,'We are pretty excited about the upcoming release of Dire Wolf Beta, just repost this sign for a chance at a key.','John Dickenson','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_162.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_162_premium.gif','enUS','Adjacent minions have +1_Attack.','AdjacentBuff','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_162',985,'Dire Wolf Alpha','Classic','Minion','Neutral','Common',2,2,2,'We are pretty excited about the upcoming release of Dire Wolf Beta, just repost this sign for a chance at a key.','John Dickenson','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_162.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_162_premium.gif','enUS','Adjacent minions have +1_Attack.','Aura','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('NEW1_023',609,'Faerie Dragon','Classic','Minion',NULL,'Common',2,3,2,'Adorable. Immune to Magic. Doesn''t pee on the rug. The perfect pet!','Samwise','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/NEW1_023.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/NEW1_023_premium.gif','enUS','Can''t be targeted by spells or Hero Powers.',NULL,'Dragon',NULL,NULL,NULL);
INSERT INTO minions VALUES ('NEW1_040t',460,'Gnoll','Classic','Minion',NULL,NULL,2,2,2,NULL,NULL,NULL,'Neutral','http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_040t.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/NEW1_040t_premium.gif','enUS','Taunt','Taunt',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_341',797,'Lightwell','Classic','Minion','Neutral','Rare',2,0,5,'It isn''t clear if people ignore the Lightwell, or if it is just invisible.','Blizzard Entertainment','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_341.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_341_premium.gif','enUS','At the start of your turn, restore 3 Health to a damaged friendly character.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_096',251,'Loot Hoarder','Classic','Minion','Neutral','Common',2,2,1,'Always roll need.','Jim Nelson','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_096.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_096_premium.gif','enUS','Deathrattle: Draw a card.','Deathrattle',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_082',762,'Mad Bomber','Classic','Minion','Alliance','Common',2,3,2,'He''s not really all that crazy, he is just not as careful with explosives as he should be.','Mike Sass','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_082.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_082_premium.gif','enUS','Battlecry: Deal 3 damage randomly split between all other characters.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('NEW1_037',351,'Master Swordsmith','Classic','Minion',NULL,'Rare',2,1,3,'He''s currently trying to craft a "flail-axe", but all the other swordsmiths say it can''t be done.','E.M. Gist','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/NEW1_037.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/NEW1_037_premium.gif','enUS','At the end of your turn, give another random friendly minion +1 Attack.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_058',891,'Sunfury Protector','Classic','Minion','Alliance','Rare',2,2,3,'She carries a shield, but only so she can give it to someone she can stand behind.','James Ryman','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_058.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_058_premium.gif','enUS','Battlecry: Give adjacent minions Taunt.','Taunt',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_058',891,'Sunfury Protector','Classic','Minion','Alliance','Rare',2,2,3,'She carries a shield, but only so she can give it to someone she can stand behind.','James Ryman','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_058.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_058_premium.gif','enUS','Battlecry: Give adjacent minions Taunt.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_049',415,'Youthful Brewmaster','Classic','Minion','Alliance','Common',2,3,2,'His youthful enthusiasm doesn’t always equal excellence in his brews. Don’t drink the Mogu Stout!','Wei Wang','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_049.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_049_premium.gif','enUS','Battlecry: Return a friendly minion from the battlefield to your hand.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_007',1659,'Acolyte of Pain','Classic','Minion',NULL,'Common',3,1,3,'He trained when he was younger to be an acolyte of joy, but things didn’t work out like he thought they would.','Dave Kendall','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_007.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_007_premium.gif','enUS','Whenever this minion takes damage, draw a_card.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_006',1658,'Alarm-o-Bot','Classic','Minion',NULL,'Rare',3,0,3,'WARNING. WARNING. WARNING.','Sean O’Daniels','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_006.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_006_premium.gif','enUS','[x]At the start of your turn,\nswap this minion with a\n random one in your hand.',NULL,'Mech',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_382',1167,'Aldor Peacekeeper','Classic','Minion','Neutral','Rare',3,3,3,'The Aldor hate two things: the Scryers and smooth jazz.','Dany Orizio','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_382.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_382_premium.gif','enUS','Battlecry: Change an_enemy minion''s Attack to 1.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_089',466,'Arcane Golem','Classic','Minion','Neutral','Rare',3,4,4,'Having Arcane golems at home really classes up the place, and as a bonus they are great conversation pieces.','Sedhayu Ardian','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_089.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_089_premium.gif','enUS','Battlecry: Give your opponent a Mana Crystal.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_590',755,'Blood Knight','Classic','Minion','Neutral','Epic',3,3,3,'The Blood Knights get their holy powers from the Sunwell, which you should NOT bathe in.','Trent Kaniuga','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_590.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_590_premium.gif','enUS','Battlecry: All minions lose Divine Shield. Gain +3/+3 for each Shield lost.','Divine Shield',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_590',755,'Blood Knight','Classic','Minion','Neutral','Epic',3,3,3,'The Blood Knights get their holy powers from the Sunwell, which you should NOT bathe in.','Trent Kaniuga','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_590.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_590_premium.gif','enUS','Battlecry: All minions lose Divine Shield. Gain +3/+3 for each Shield lost.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_103',453,'Coldlight Seer','Classic','Minion','Neutral','Rare',3,2,3,'The Coldlight murlocs reside in the darkest pits of the Abyssal Depths. So no, there''s no getting away from murlocs.','Arthur Gimaldinov','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_103.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_103_premium.gif','enUS','Battlecry: Give your other Murlocs +2 Health.','Battlecry','Murloc',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_102',979,'Demolisher','Classic','Minion','Neutral','Rare',3,1,4,'Laying siege isn''t fun for anyone. It''s not even all that effective, now that everyone has a flying mount.','Raymond Swanland','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_102.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_102_premium.gif','enUS','At the start of your turn, deal 2 damage to a random enemy.',NULL,'Mech',NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_117',1651,'Earthen Ring Farseer','Classic','Minion',NULL,'Common',3,3,3,'He can see really far, and he doesn''t use a telescope like those filthy pirates.','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_117.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_117_premium.gif','enUS','Battlecry: Restore 3_Health.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_170',1098,'Emperor Cobra','Classic','Minion','Neutral','Rare',3,2,3,'The Sholazar Basin is home to a lot of really horrible things. If you''re going to visit, wear bug spray. And plate armor.','Lars Grant-West','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_170.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_170_premium.gif','enUS','Poisonous','Poisonous','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_301',517,'Felguard','Classic','Minion','Neutral','Rare',3,3,5,'Yes, he''ll fight for you. BUT HE''S NOT GOING TO LIKE IT.','John Polidora','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_301.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_301_premium.gif','enUS','Taunt\nBattlecry: Destroy one of your Mana Crystals.','Taunt','Demon',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_301',517,'Felguard','Classic','Minion','Neutral','Rare',3,3,5,'Yes, he''ll fight for you. BUT HE''S NOT GOING TO LIKE IT.','John Polidora','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_301.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_301_premium.gif','enUS','Taunt\nBattlecry: Destroy one of your Mana Crystals.','Battlecry','Demon',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_finkle',1006,'Finkle Einhorn','Classic','Minion','Neutral',NULL,3,3,3,NULL,NULL,NULL,'Neutral','http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_finkle.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/EX1_finkle_premium.gif','enUS',NULL,NULL,NULL,'True',NULL,NULL);
INSERT INTO minions VALUES ('tt_004',397,'Flesheating Ghoul','Classic','Minion','Neutral','Common',3,2,3,'''Flesheating'' is an unfair name. It''s just that there''s not really much else for him to eat.','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/tt_004.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/tt_004_premium.gif','enUS','Whenever a minion dies, gain +1 Attack.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_604',654,'Frothing Berserker','Classic','Minion','Neutral','Rare',3,2,4,'He used to work as an accountant before he tried his hand at Berserkering.','Simon Bisley','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_604.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_604_premium.gif','enUS','Whenever a minion takes damage, gain +1 Attack.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_181',1109,'Injured Blademaster','Classic','Minion','Horde','Rare',3,4,7,'He claims it is an old war wound, but we think he just cut himself shaving.','Samwise','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_181.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_181_premium.gif','enUS','Battlecry: Deal 4 damage to HIMSELF.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_203',290,'Ironbeak Owl','Classic','Minion','Horde','Common',3,2,1,'Their wings are silent but their screech is... whatever the opposite of silent is.','Trevor Jacobs','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_203.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_203_premium.gif','enUS','Battlecry: Silence a_minion.','Silence','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_203',290,'Ironbeak Owl','Classic','Minion','Horde','Common',3,2,1,'Their wings are silent but their screech is... whatever the opposite of silent is.','Trevor Jacobs','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_203.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_203_premium.gif','enUS','Battlecry: Silence a_minion.','Battlecry','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_017',921,'Jungle Panther','Classic','Minion','Horde','Common',3,4,2,'Stranglethorn is a beautiful place to visit, but you wouldn''t want to live there.','Jaemin Kim','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_017.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_017_premium.gif','enUS','Stealth','Stealth','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_507',1063,'Murloc Warleader','Classic','Minion','Neutral','Epic',3,3,3,'Do Murlocs ever get tired of making the same old sound? Nope! Mrglglrglglglglglglgl!','Tim McBurnie','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_507.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_507_premium.gif','enUS','Your other Murlocs have +2 Attack.','Aura','Murloc',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_412',1155,'Raging Worgen','Classic','Minion','Neutral','Common',3,3,3,'If he''s raging now, just wait until he gets nerfed.','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_412.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_412_premium.gif','enUS','Has +1 Attack and Windfury while damaged.','Windfury',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_020',642,'Scarlet Crusader','Classic','Minion','Alliance','Common',3,3,1,'Never wash your whites with a Scarlet Crusader.','Gonzalo Ordonez','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_020.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_020_premium.gif','enUS','Divine Shield','Divine Shield',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('NEW1_027',680,'Southsea Captain','Classic','Minion',NULL,'Epic',3,3,3,'When he saves enough plunder, he''s going to commission an enormous captain''s hat. He has hat envy.','Ken Steacy','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/NEW1_027.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/NEW1_027_premium.gif','enUS','Your other Pirates have +1/+1.','Aura','Pirate',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_390',45,'Tauren Warrior','Classic','Minion','Neutral','Common',3,2,3,'Tauren Warrior: Champion of Mulgore, Slayer of Quilboar, Rider of Thunderbluff Elevators.','Paul Warzecha','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_390.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_390_premium.gif','enUS','Taunt\nHas +3 Attack while damaged.','Taunt',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_021',765,'Thrallmar Farseer','Classic','Minion','Horde','Common',3,2,3,'He''s stationed in the Hellfire Peninsula, but he''s hoping for a reassignment closer to Orgrimmar, or really anywhere the ground is less on fire.','Efrem Palacios','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_021.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_021_premium.gif','enUS','Windfury','Windfury',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_304',1221,'Void Terror','Classic','Minion',NULL,'Rare',3,3,3,'If you put this into your deck, you WILL lose the trust of your other minions.','Alexander Alexandrov','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_304.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_304_premium.gif','enUS','[x]Battlecry: Destroy both\nadjacent minions and gain\n their Attack and Health.','Battlecry','Demon',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_057',186,'Ancient Brewmaster','Classic','Minion','Alliance','Common',4,5,4,'Most pandaren say his brew tastes like yak. But apparently that''s a compliment.','Bernie Kang','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_057.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_057_premium.gif','enUS','Battlecry: Return a friendly minion from the battlefield to your hand.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_584',915,'Ancient Mage','Classic','Minion','Neutral','Rare',4,2,5,'Sometimes he forgets and just wanders into someone else''s game.','Howard Lyon','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_584.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_584_premium.gif','enUS','Battlecry: Give adjacent_minions Spell_Damage +1.','Spell Damage',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_584',915,'Ancient Mage','Classic','Minion','Neutral','Rare',4,2,5,'Sometimes he forgets and just wanders into someone else''s game.','Howard Lyon','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_584.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_584_premium.gif','enUS','Battlecry: Give adjacent_minions Spell_Damage +1.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_046',348,'Dark Iron Dwarf','Classic','Minion','Alliance','Common',4,4,4,'Guardians of Dark Iron Ore. Perhaps the most annoying ore, given where you have to forge it.','Scott Hampton','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_046.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_046_premium.gif','enUS','Battlecry: Give a minion +2_Attack this turn.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_093',763,'Defender of Argus','Classic','Minion','Alliance','Rare',4,2,3,'You wouldn’t think that Argus would need this much defending. But it does.','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_093.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_093_premium.gif','enUS','Battlecry: Give adjacent minions +1/+1 and Taunt.','Taunt',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_093',763,'Defender of Argus','Classic','Minion','Alliance','Rare',4,2,3,'You wouldn’t think that Argus would need this much defending. But it does.','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_093.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_093_premium.gif','enUS','Battlecry: Give adjacent minions +1/+1 and Taunt.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_396',700,'Mogu''shan Warden','Classic','Minion','Neutral','Common',4,1,7,'All these guys ever do is talk about the Thunder King. BOOOORRRINNG!','Cole Eastburn','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_396.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_396_premium.gif','enUS','Taunt','Taunt',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_313',783,'Pit Lord','Classic','Minion','Neutral','Epic',4,5,6,'Mannoroth, Magtheridon, and Brutallus may be dead, but it turns out there are a LOT of pit lords.','Glenn Rane','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_313.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_313_premium.gif','enUS','Battlecry: Deal 5 damage to your hero.','Battlecry','Demon',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_023',34,'Silvermoon Guardian','Classic','Minion','Horde','Common',4,3,3,'The first time they tried to guard Silvermoon against the scourge, it didn’t go so well…','Phroilan Gardner','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_023.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_023_premium.gif','enUS','Divine Shield','Divine Shield',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_048',754,'Spellbreaker','Classic','Minion','Horde','Common',4,4,3,'Spellbreakers can rip enchantments from magic-wielders. The process is painless and can be performed on an outpatient basis.','Matt Cavotta','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_048.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_048_premium.gif','enUS','Battlecry: Silence a_minion.','Silence',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_048',754,'Spellbreaker','Classic','Minion','Horde','Common',4,4,3,'Spellbreakers can rip enchantments from magic-wielders. The process is painless and can be performed on an outpatient basis.','Matt Cavotta','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_048.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_048_premium.gif','enUS','Battlecry: Silence a_minion.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_043',1037,'Twilight Drake','Classic','Minion','Neutral','Rare',4,4,1,'Twilight drakes feed on Mystical Energy. And Tacos.','Jaemin Kim','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_043.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_043_premium.gif','enUS','Battlecry: Gain +1 Health for each card in your hand.','Battlecry','Dragon',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_097',440,'Abomination','Classic','Minion','Neutral','Rare',5,4,4,'Abominations enjoy Fresh Meat and long walks on the beach.','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_097.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_097_premium.gif','enUS','Taunt. Deathrattle: Deal 2\ndamage to ALL characters.','Taunt',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_097',440,'Abomination','Classic','Minion','Neutral','Rare',5,4,4,'Abominations enjoy Fresh Meat and long walks on the beach.','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_097.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_097_premium.gif','enUS','Taunt. Deathrattle: Deal 2\ndamage to ALL characters.','Deathrattle',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_005',1657,'Big Game Hunter','Classic','Minion',NULL,'Epic',5,4,2,'Mere devilsaurs no longer excite him. Soon he''ll be trying to catch Onyxia with only a dull Krol Blade.','Chris Seaman','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_005.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_005_premium.gif','enUS','Battlecry: Destroy a minion with 7 or more Attack.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('NEW1_024',456,'Captain Greenskin','Classic','Minion',NULL,'Legendary',5,5,4,'He was this close to piloting a massive juggernaut into Stormwind Harbor. If it weren''t for those pesky kids!','Dan Scott','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/NEW1_024.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/NEW1_024_premium.gif','enUS','Battlecry: Give your weapon +1/+1.','Battlecry','Pirate','True',NULL,NULL);
INSERT INTO minions VALUES ('CS1_069',602,'Fen Creeper','Classic','Minion','Alliance','Common',5,3,6,'He used to be called Bog Beast, but it confused people because he wasn''t an actual beast. Boom, New Name!','Monica Langlois','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS1_069.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS1_069_premium.gif','enUS','Taunt','Taunt',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_558',912,'Harrison Jones','Classic','Minion','Neutral','Legendary',5,5,4,'“That belongs in the Hall of Explorers!”','Matt Dixon','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_558.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_558_premium.gif','enUS','Battlecry: Destroy your opponent''s weapon and draw cards equal to its Durability.','Battlecry',NULL,'True',NULL,NULL);
INSERT INTO minions VALUES ('CS2_221',61,'Spiteful Smith','Classic','Minion','Horde','Common',5,4,6,'She''ll craft you a sword, but you''ll need to bring her 5 Steel Ingots, 3 Motes of Earth, and the scalp of her last customer.','Justin Sweet','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_221.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_221_premium.gif','enUS','Your weapon has +2 Attack while this is damaged.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('NEW1_041',1371,'Stampeding Kodo','Classic','Minion',NULL,'Rare',5,3,5,'This Kodo is so big that he can stampede by himself.','Daren Bader','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/NEW1_041.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/NEW1_041_premium.gif','enUS','Battlecry: Destroy a random enemy minion with 2 or less Attack.','Battlecry','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_028',68,'Stranglethorn Tiger','Classic','Minion','Alliance','Common',5,5,5,'The wonderful thing about tigers is tigers are wonderful things!','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_028.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_028_premium.gif','enUS','Stealth','Stealth','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_067',281,'Argent Commander','Classic','Minion','Neutral','Rare',6,4,2,'The Argent Dawn stands vigilant against the Scourge, as well as people who cut in line at coffee shops.','James Ryman','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_067.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_067_premium.gif','enUS','Charge\nDivine Shield','Charge',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_067',281,'Argent Commander','Classic','Minion','Neutral','Rare',6,4,2,'The Argent Dawn stands vigilant against the Scourge, as well as people who cut in line at coffee shops.','James Ryman','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_067.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_067_premium.gif','enUS','Charge\nDivine Shield','Divine Shield',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_tk34',1143,'Infernal','Classic','Minion','Neutral',NULL,6,6,6,NULL,NULL,NULL,'Warlock','http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_tk34.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/EX1_tk34_premium.gif','enUS',NULL,NULL,'Demon',NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_583',424,'Priestess of Elune','Classic','Minion','Neutral','Common',6,5,4,'If she threatens to "moon" you, it''s not what you think.','Dan Scott','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_583.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_583_premium.gif','enUS','Battlecry: Restore 4 Health to your hero.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_032',759,'Sunwalker','Classic','Minion','Alliance','Rare',6,4,5,'She doesn’t ACTUALLY walk on the Sun. It''s just a name. Don’t worry!','Andrea Uderzo','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_032.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_032_premium.gif','enUS','Taunt\nDivine Shield','Taunt',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_032',759,'Sunwalker','Classic','Minion','Alliance','Rare',6,4,5,'She doesn’t ACTUALLY walk on the Sun. It''s just a name. Don’t worry!','Andrea Uderzo','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_032.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_032_premium.gif','enUS','Taunt\nDivine Shield','Divine Shield',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_623',1364,'Temple Enforcer','Classic','Minion',NULL,'Common',6,6,6,'He also moonlights Thursday nights as a bouncer at the Pig and Whistle Tavern.','Daren Bader','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_623.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_623_premium.gif','enUS','Battlecry: Give a friendly minion +3 Health.','Battlecry',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_002',1656,'The Black Knight','Classic','Minion',NULL,'Legendary',6,4,5,'He was sent by the Lich King to disrupt the Argent Tournament. We can pretty much mark that a failure.','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_002.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_002_premium.gif','enUS','Battlecry: Destroy an enemy minion with Taunt.','Taunt',NULL,'True',NULL,NULL);
INSERT INTO minions VALUES ('EX1_002',1656,'The Black Knight','Classic','Minion',NULL,'Legendary',6,4,5,'He was sent by the Lich King to disrupt the Argent Tournament. We can pretty much mark that a failure.','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_002.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_002_premium.gif','enUS','Battlecry: Destroy an enemy minion with Taunt.','Battlecry',NULL,'True',NULL,NULL);
INSERT INTO minions VALUES ('EX1_033',567,'Windfury Harpy','Classic','Minion','Alliance','Common',6,4,5,'Harpies are not pleasant sounding. That''s the nicest I can put it.','Luke Mancini','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_033.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_033_premium.gif','enUS','Windfury','Windfury',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_249',336,'Baron Geddon','Classic','Minion','Neutral','Legendary',7,7,5,'Baron Geddon was Ragnaros''s foremost lieutenant, until he got FIRED.','Ian Ameling','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_249.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_249_premium.gif','enUS','At the end of your turn, deal 2 damage to ALL other characters.',NULL,'Elemental','True',NULL,NULL);
INSERT INTO minions VALUES ('EX1_350',9,'Prophet Velen','Classic','Minion','Neutral','Legendary',7,7,7,'He''s been exiled from his home, and all his brothers turned evil, but otherwise he doesn''t have a lot to complain about.','Wei Wang','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_350.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_350_premium.gif','enUS','Double the damage and healing of your spells and Hero Power.',NULL,NULL,'True',NULL,NULL);
INSERT INTO minions VALUES ('CS2_161',134,'Ravenholdt Assassin','Classic','Minion','Alliance','Rare',7,7,5,'Just mail him a package with a name and 10,000 gold. He''ll take care of the rest.','Ralph Horsley','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_161.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_161_premium.gif','enUS','Stealth','Stealth',NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('EX1_414',338,'Grommash Hellscream','Classic','Minion','Neutral','Legendary',8,4,9,'Grommash drank the tainted blood of Mannoroth, dooming the orcs to green skin and red eyes! Maybe not his best decision.','Glenn Rane','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_414.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_414_premium.gif','enUS','Charge\nHas +6 Attack while damaged.','Charge',NULL,'True',NULL,NULL);
INSERT INTO minions VALUES ('NEW1_038',526,'Gruul','Classic','Minion',NULL,'Legendary',8,7,7,'He''s Gruul "the Dragonkiller". He just wanted to cuddle them… he never meant to…','Kev Walker','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/NEW1_038.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/NEW1_038_premium.gif','enUS','At the end of each turn, gain +1/+1 .',NULL,NULL,'True',NULL,NULL);
INSERT INTO minions VALUES ('EX1_561',581,'Alexstrasza','Classic','Minion','Neutral','Legendary',9,8,8,'Alexstrasza the Life-Binder brings life and hope to everyone. Except Deathwing. And Malygos. And Nekros.','Raymond Swanland','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_561.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_561_premium.gif','enUS','Battlecry: Set a hero''s remaining Health to 15.','Battlecry','Dragon','True',NULL,NULL);
INSERT INTO minions VALUES ('EX1_543',1144,'King Krush','Classic','Minion','Neutral','Legendary',9,8,8,'The best defense against King Krush is to have someone you don’t like standing in front of you.','Alex Horley Orlandelli','True','Hunter','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_543.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_543_premium.gif','enUS','Charge','Charge','Beast','True',NULL,NULL);
INSERT INTO minions VALUES ('EX1_563',436,'Malygos','Classic','Minion','Neutral','Legendary',9,4,12,'Malygos hates it when mortals use magic. He gets so mad!','Michael Komarck','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_563.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_563_premium.gif','enUS','Spell Damage +5','Spell Damage','Dragon','True',NULL,NULL);
INSERT INTO minions VALUES ('EX1_560',411,'Nozdormu','Classic','Minion','Neutral','Legendary',9,8,8,'Time to write some flavor text.','James Ryman','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_560.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_560_premium.gif','enUS','Players only have 15 seconds to take their_turns.',NULL,'Dragon','True',NULL,NULL);
INSERT INTO minions VALUES ('EX1_586',211,'Sea Giant','Classic','Minion','Neutral','Epic',10,8,8,'See? Giant.','Svetlin Velinov','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_586.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_586_premium.gif','enUS','Costs (1) less for each other minion on the battlefield.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('GAME_002',1733,'Avatar of the Coin','Basic','Minion',NULL,'Free',0,1,1,NULL,NULL,NULL,'Neutral','http://wow.zamimg.com/images/hearthstone/cards/enus/original/GAME_002.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/GAME_002_premium.gif','enUS','You lost the coin flip, but gained a friend.',NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_boar',298,'Boar','Basic','Minion','Neutral','Common',1,1,1,NULL,NULL,NULL,'Neutral','http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_boar.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/CS2_boar_premium.gif','enUS',NULL,NULL,'Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_189',389,'Elven Archer','Basic','Minion','Horde','Free',1,1,1,'Don''t bother asking her out on a date. She''ll shoot you down.','Steve Prescott','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_189.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_189_premium.gif','enUS','Battlecry: Deal 1 damage.','Battlecry',NULL,NULL,'Unlocked at Druid Level 57.',NULL);
INSERT INTO minions VALUES ('CS1_042',922,'Goldshire Footman','Basic','Minion','Alliance','Free',1,1,2,'If 1/2 minions are all that is defending Goldshire, you would think it would have been overrun years ago.','Donato Giancola','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS1_042.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS1_042_premium.gif','enUS','Taunt','Taunt',NULL,NULL,'Unlocked at Paladin Level 57.',NULL);
INSERT INTO minions VALUES ('EX1_508',510,'Grimscale Oracle','Basic','Minion','Neutral','Free',1,1,1,'These are the brainy murlocs. It turns out that doesn’t mean much.','Phil Saunders','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_508.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_508_premium.gif','enUS','Your other Murlocs have +1 Attack.',NULL,'Murloc',NULL,'Unlocked at Warlock Level 53.',NULL);
INSERT INTO minions VALUES ('EX1_025t',59,'Mechanical Dragonling','Basic','Minion','Neutral','Common',1,2,1,NULL,NULL,NULL,'Neutral','http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_025t.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/EX1_025t_premium.gif','enUS',NULL,NULL,'Mech',NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_168',191,'Murloc Raider','Basic','Minion','Alliance','Free',1,2,1,'Mrrraggglhlhghghlgh, mrgaaag blarrghlgaahahl mrgggg glhalhah a bghhll graggmgmg Garrosh mglhlhlh mrghlhlhl!!','Dan Scott','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_168.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_168_premium.gif','enUS',NULL,NULL,'Murloc',NULL,'Unlocked at Priest Level 51.',NULL);
INSERT INTO minions VALUES ('EX1_506a',1078,'Murloc Scout','Basic','Minion','Neutral','Common',1,1,1,NULL,NULL,NULL,'Neutral','http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_506a.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/EX1_506a_premium.gif','enUS',NULL,NULL,'Murloc',NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_235',1650,'Northshire Cleric','Basic','Minion',NULL,'Free',1,1,3,'They help the downtrodden and distressed. Also they sell cookies.','Terese Nielsen','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_235.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_235_premium.gif','enUS','Whenever a minion is healed, draw a card.',NULL,NULL,NULL,'Unlocked at Level 40.','Unlocked at Level 1.');
INSERT INTO minions VALUES ('CS2_tk1',796,'Sheep','Basic','Minion','Neutral','Common',1,1,1,NULL,NULL,NULL,'Neutral','http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_tk1.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/CS2_tk1_premium.gif','enUS',NULL,NULL,'Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_101t',1652,'Silver Hand Recruit','Basic','Minion',NULL,'Free',1,1,1,NULL,NULL,NULL,'Paladin','http://wow.zamimg.com/images/hearthstone/cards/enus/original/CS2_101t.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/CS2_101t_premium.gif','enUS',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_171',648,'Stonetusk Boar','Basic','Minion','Neutral','Free',1,1,1,'This card is boaring.','Howard Lyon','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_171.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_171_premium.gif','enUS','Charge','Charge','Beast',NULL,'Unlocked at Hunter Level 53.',NULL);
INSERT INTO minions VALUES ('DS1_175',606,'Timber Wolf','Basic','Minion','Neutral','Free',1,1,1,'Other beasts totally dig hanging out with timber wolves.','Malcolm Davis','True','Hunter','http://media.services.zam.com/v1/media/byName/hs/cards/enus/DS1_175.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/DS1_175_premium.gif','enUS','Your other Beasts have +1_Attack.','Aura','Beast',NULL,'Unlocked at Level 23.','Unlocked at Level 1.');
INSERT INTO minions VALUES ('CS2_065',48,'Voidwalker','Basic','Minion','Neutral','Free',1,1,3,'No relation to "The Voidsteppers", the popular Void-based dance troupe.','Alex Horley Orlandelli','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_065.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_065_premium.gif','enUS','Taunt','Taunt','Demon',NULL,'Unlocked at Level 36.','Unlocked at Level 1.');
INSERT INTO minions VALUES ('EX1_011',132,'Voodoo Doctor','Basic','Minion','Horde','Free',1,2,1,'Voodoo is an oft-misunderstood art. But it is art.','Karl Richardson','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_011.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_011_premium.gif','enUS','Battlecry: Restore 2_Health.','Battlecry',NULL,NULL,'Unlocked at Rogue Level 55.',NULL);
INSERT INTO minions VALUES ('CS2_172',216,'Bloodfen Raptor','Basic','Minion','Horde','Free',2,3,2,'"Kill 30 raptors." - Hemet Nesingwary','Dan Brereton','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_172.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_172_premium.gif','enUS',NULL,NULL,'Beast',NULL,'Unlocked at Hunter Level 57.',NULL);
INSERT INTO minions VALUES ('CS2_173',739,'Bluegill Warrior','Basic','Minion','Neutral','Free',2,2,1,'He just wants a hug. A sloppy... slimy... hug.','Jakub Kasper','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_173.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_173_premium.gif','enUS','Charge','Charge','Murloc',NULL,'Unlocked at Paladin Level 53.',NULL);
INSERT INTO minions VALUES ('CS2_121',41,'Frostwolf Grunt','Basic','Minion','Neutral','Free',2,2,2,'Grunting is what his father did and his father before that. It''s more than just a job.','Richie Marella','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_121.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_121_premium.gif','enUS','Taunt','Taunt',NULL,NULL,'Unlocked at Shaman Level 57.',NULL);
INSERT INTO minions VALUES ('CS2_142',672,'Kobold Geomancer','Basic','Minion','Horde','Free',2,2,2,'In the old days, Kobolds were the finest candle merchants in the land. Then they got pushed too far...','Gabor Szikszai','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_142.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_142_premium.gif','enUS','Spell Damage +1','Spell Damage',NULL,NULL,'Unlocked at Warlock Level 59.',NULL);
INSERT INTO minions VALUES ('EX1_015',284,'Novice Engineer','Basic','Minion','Alliance','Free',2,1,1,'"Half of this class will not graduate… since they''ll have been turned to chickens." - Tinkmaster Overspark, teaching Gizmos 101.','Karl Richardson','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_015.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_015_premium.gif','enUS','Battlecry: Draw a card.','Battlecry',NULL,NULL,'Unlocked at Druid Level 59.',NULL);
INSERT INTO minions VALUES ('CS2_120',1369,'River Crocolisk','Basic','Minion',NULL,'Free',2,2,3,'Edward "Lefty" Smith tried to make luggage out of a river crocolisk once.','Daren Bader','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_120.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_120_premium.gif','enUS',NULL,NULL,'Beast',NULL,'Unlocked at Druid Level 55.',NULL);
INSERT INTO minions VALUES ('EX1_306',592,'Succubus','Basic','Minion','Neutral','Free',2,4,3,'Warlocks have it pretty good.','Matt Dixon','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_306.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_306_premium.gif','enUS','Battlecry: Discard a random card.','Battlecry','Demon',NULL,'Unlocked at Level 40.','Unlocked at Level 1.');
INSERT INTO minions VALUES ('EX1_582',175,'Dalaran Mage','Basic','Minion','Neutral','Free',3,1,4,'You don''t see a lot of Dalaran warriors.','Jim Nelson','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_582.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_582_premium.gif','enUS','Spell Damage +1','Spell Damage',NULL,NULL,'Unlocked at Mage Level 59.',NULL);
INSERT INTO minions VALUES ('NEW1_034',100,'Huffer','Basic','Minion',NULL,'Common',3,4,2,NULL,NULL,NULL,'Hunter','http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_034.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/NEW1_034_premium.gif','enUS','Charge','Charge','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_141',339,'Ironforge Rifleman','Basic','Minion','Alliance','Free',3,2,2,'"Ready! Aim! Drink!"','Tooth','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_141.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_141_premium.gif','enUS','Battlecry: Deal 1 damage.','Battlecry',NULL,NULL,'Unlocked at Mage Level 55.',NULL);
INSERT INTO minions VALUES ('CS2_125',1182,'Ironfur Grizzly','Basic','Minion','Neutral','Free',3,3,3,'"Bear Carcass 1/10"','Lars Grant-West','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_125.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_125_premium.gif','enUS','Taunt','Taunt','Beast',NULL,'Unlocked at Hunter Level 59.',NULL);
INSERT INTO minions VALUES ('NEW1_033',226,'Leokk','Basic','Minion',NULL,'Common',3,2,4,NULL,NULL,NULL,'Hunter','http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_033.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/NEW1_033_premium.gif','enUS','Your other minions have +1 Attack.','Aura','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_118',1653,'Magma Rager','Basic','Minion',NULL,'Free',3,5,1,'He likes to think he is powerful, but pretty much anyone can solo Molten Core now.','Matt Gaser','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_118.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_118_premium.gif','enUS',NULL,NULL,'Elemental',NULL,'Unlocked at Shaman Level 51.',NULL);
INSERT INTO minions VALUES ('NEW1_032',959,'Misha','Basic','Minion',NULL,'Common',3,4,4,NULL,NULL,NULL,'Hunter','http://wow.zamimg.com/images/hearthstone/cards/enus/original/NEW1_032.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/NEW1_032_premium.gif','enUS','Taunt','Taunt','Beast',NULL,NULL,NULL);
INSERT INTO minions VALUES ('CS2_122',1401,'Raid Leader','Basic','Minion',NULL,'Free',3,2,2,'"That''s a 50 DKP minus!"','Phill Gonzales','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_122.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_122_premium.gif','enUS','Your other minions have +1 Attack.','Aura',NULL,NULL,'Unlocked at Warrior Level 57.',NULL);
INSERT INTO minions VALUES ('EX1_019',608,'Shattered Sun Cleric','Basic','Minion','Neutral','Free',3,3,2,'They always have a spare flask of Sunwell Energy Drink™!','Doug Alexander','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_019.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_019_premium.gif','enUS','Battlecry: Give a friendly minion +1/+1.','Battlecry',NULL,NULL,'Unlocked at Priest Level 53.',NULL);
INSERT INTO minions VALUES ('CS2_127',67,'Silverback Patriarch','Basic','Minion','Horde','Free',3,1,4,'He likes to act like he''s in charge, but the silverback matriarch actually runs things.','Daren Bader','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_127.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_127_premium.gif','enUS','Taunt','Taunt','Beast',NULL,'Unlocked at Warrior Level 53.',NULL);
INSERT INTO minions VALUES ('EX1_084',1009,'Warsong Commander','Basic','Minion','Neutral','Free',3,2,3,'The Warsong clan is such drama. It''s really not worth it to become a commander.','Wei Wang','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_084.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_084_premium.gif','enUS','Your Charge minions have +1 Attack.','Charge',NULL,NULL,'Unlocked at Level 36.','Unlocked at Level 1.');
INSERT INTO minions VALUES ('EX1_084',1009,'Warsong Commander','Basic','Minion','Neutral','Free',3,2,3,'The Warsong clan is such drama. It''s really not worth it to become a commander.','Wei Wang','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_084.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_084_premium.gif','enUS','Your Charge minions have +1 Attack.','Aura',NULL,NULL,'Unlocked at Level 36.','Unlocked at Level 1.');
INSERT INTO minions VALUES ('CS2_124',289,'Wolfrider','Basic','Minion','Horde','Free',3,3,1,'Orcish raiders ride wolves because they are well adapted to harsh environments, and because they are soft and cuddly.','Dany Orizio','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_124.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_124_premium.gif','enUS','Charge','Charge',NULL,NULL,'Unlocked at Warrior Level 59.',NULL);
INSERT INTO minions VALUES ('CS2_182',90,'Chillwind Yeti','Basic','Minion','Neutral','Free',4,4,5,'He always dreamed of coming down from the mountains and opening a noodle shop, but he never got the nerve.','Mauro Cascioli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_182.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_182_premium.gif','enUS',NULL,NULL,NULL,NULL,'Unlocked at Warrior Level 55.',NULL);
INSERT INTO minions VALUES ('CS2_147',308,'Gnomish Inventor','Basic','Minion','Alliance','Free',4,2,4,'She''s never quite sure what she''s making, she just knows it''s AWESOME!','Court Jones','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_147.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_147_premium.gif','enUS','Battlecry: Draw a card.','Battlecry',NULL,NULL,'Unlocked at Priest Level 57.',NULL);
INSERT INTO minions VALUES ('DS1_070',1003,'Houndmaster','Basic','Minion','Neutral','Free',4,4,3,'"Who let the dogs out?" he asks. It''s rhetorical.','Dan Brereton','True','Hunter','http://media.services.zam.com/v1/media/byName/hs/cards/enus/DS1_070.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/DS1_070_premium.gif','enUS','Battlecry: Give a friendly Beast +2/+2 and Taunt.','Taunt',NULL,NULL,'Unlocked at Level 28.','Unlocked at Level 1.');
INSERT INTO minions VALUES ('DS1_070',1003,'Houndmaster','Basic','Minion','Neutral','Free',4,4,3,'"Who let the dogs out?" he asks. It''s rhetorical.','Dan Brereton','True','Hunter','http://media.services.zam.com/v1/media/byName/hs/cards/enus/DS1_070.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/DS1_070_premium.gif','enUS','Battlecry: Give a friendly Beast +2/+2 and Taunt.','Battlecry',NULL,NULL,'Unlocked at Level 28.','Unlocked at Level 1.');
INSERT INTO minions VALUES ('NEW1_011',28,'Kor''kron Elite','Basic','Minion',NULL,'Free',4,4,3,'The Kor''kron are the elite forces of Garrosh Hellscream. Let''s just say you don''t want to run into these guys while wearing a blue tabard.','Alex Horley Orlandelli','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/NEW1_011.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/NEW1_011_premium.gif','enUS','Charge','Charge',NULL,NULL,'Unlocked at Level 44.','Unlocked at Level 4.');
INSERT INTO minions VALUES ('CS2_119',1370,'Oasis Snapjaw','Basic','Minion',NULL,'Free',4,2,7,'His dreams of flying and breathing fire like his idol will never be realized.','Ittoku','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_119.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_119_premium.gif','enUS',NULL,NULL,'Beast',NULL,'Unlocked at Druid Level 51.',NULL);
INSERT INTO minions VALUES ('CS2_197',995,'Ogre Magi','Basic','Minion','Neutral','Free',4,4,4,'Training Ogres in the art of spellcasting is a questionable decision.','James Ryman','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_197.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_197_premium.gif','enUS','Spell Damage +1','Spell Damage',NULL,NULL,'Unlocked at Warlock Level 55.',NULL);
INSERT INTO minions VALUES ('CS2_179',635,'Sen''jin Shieldmasta','Basic','Minion','Horde','Free',4,3,5,'Sen''jin Village is nice, if you like trolls and dust.','Brian Despain','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_179.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_179_premium.gif','enUS','Taunt','Taunt',NULL,NULL,'Unlocked at Rogue Level 59.',NULL);
INSERT INTO minions VALUES ('CS2_131',622,'Stormwind Knight','Basic','Minion','Alliance','Free',4,2,5,'They''re still embarrassed about "The Deathwing Incident".','Ladronn','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_131.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_131_premium.gif','enUS','Charge','Charge',NULL,NULL,'Unlocked at Paladin Level 55.',NULL);
INSERT INTO minions VALUES ('CS2_187',1140,'Booty Bay Bodyguard','Basic','Minion','Horde','Free',5,5,4,'You can hire him... until someone offers him enough gold to turn on you.','Matt Cavotta','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_187.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_187_premium.gif','enUS','Taunt','Taunt',NULL,NULL,'Unlocked at Shaman Level 55.',NULL);
INSERT INTO minions VALUES ('DS1_055',582,'Darkscale Healer','Basic','Minion','Neutral','Free',5,4,5,'Healing is just something she does in her free time. It''s more of a hobby really.','Jesper Ejsing','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/DS1_055.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/DS1_055_premium.gif','enUS','Battlecry: Restore 2 Health to all friendly characters.','Battlecry',NULL,NULL,'Unlocked at Priest Level 55.',NULL);
INSERT INTO minions VALUES ('CS2_226',496,'Frostwolf Warlord','Basic','Minion','Horde','Free',5,4,4,'The Frostwolves are locked in combat with the Stormpike Expedition over control of Alterac Valley. Every attempt at peace-talks has ended with Captain Galvangar killing the mediator.','James Ryman','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_226.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_226_premium.gif','enUS','Battlecry: Gain +1/+1 for each other friendly minion on the battlefield.','Battlecry',NULL,NULL,'Unlocked at Shaman Level 53.',NULL);
INSERT INTO minions VALUES ('EX1_399',768,'Gurubashi Berserker','Basic','Minion','Neutral','Free',5,2,7,'No Pain, No Gain.','Alex Horley Orlandelli','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_399.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_399_premium.gif','enUS','Whenever this minion takes damage, gain +3_Attack.',NULL,NULL,NULL,'Unlocked at Warlock Level 57.',NULL);
INSERT INTO minions VALUES ('EX1_593',670,'Nightblade','Basic','Minion','Neutral','Free',5,4,4,'Your face is the place you''d probably least like a dagger, and where rogues are most likely to deliver them.','Raymond Swanland','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_593.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_593_premium.gif','enUS','Battlecry: Deal 3 damage to the enemy hero.','Battlecry',NULL,NULL,'Unlocked at Druid Level 53.',NULL);
INSERT INTO minions VALUES ('CS2_150',413,'Stormpike Commando','Basic','Minion','Alliance','Free',5,4,2,'The Stormpike Commandos are demolition experts. They also bake a mean cupcake.','Kev Walker','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_150.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_150_premium.gif','enUS','Battlecry: Deal 2 damage.','Battlecry',NULL,NULL,'Unlocked at Paladin Level 51.',NULL);
INSERT INTO minions VALUES ('DS1_178',699,'Tundra Rhino','Basic','Minion','Neutral','Free',5,2,5,'Tundra rhinos are often mistaken for kodos. Or am I mistaken?','Lars Grant-West','True','Hunter','http://media.services.zam.com/v1/media/byName/hs/cards/enus/DS1_178.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/DS1_178_premium.gif','enUS','Your Beasts have Charge.','Charge','Beast',NULL,'Unlocked at Level 43.','Unlocked at Level 8.');
INSERT INTO minions VALUES ('DS1_178',699,'Tundra Rhino','Basic','Minion','Neutral','Free',5,2,5,'Tundra rhinos are often mistaken for kodos. Or am I mistaken?','Lars Grant-West','True','Hunter','http://media.services.zam.com/v1/media/byName/hs/cards/enus/DS1_178.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/DS1_178_premium.gif','enUS','Your Beasts have Charge.','Aura','Beast',NULL,'Unlocked at Level 43.','Unlocked at Level 8.');
INSERT INTO minions VALUES ('CS2_155',525,'Archmage','Basic','Minion','Alliance','Free',6,4,7,'You earn the title of Archmage when you can destroy anyone who calls you on it.','Steve Ellis','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_155.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_155_premium.gif','enUS','Spell Damage +1','Spell Damage',NULL,NULL,'Unlocked at Mage Level 57.',NULL);
INSERT INTO minions VALUES ('CS2_200',1686,'Boulderfist Ogre','Basic','Minion',NULL,'Free',6,6,7,'"ME HAVE GOOD STATS FOR THE COST"','Brian Despain','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_200.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_200_premium.gif','enUS',NULL,NULL,NULL,NULL,'Unlocked at Warlock Level 51.',NULL);
INSERT INTO minions VALUES ('CS2_064',1019,'Dread Infernal','Basic','Minion','Neutral','Free',6,6,6,'"INFERNOOOOOOOOOO!" - Jaraxxus, Eredar Lord of the Burning Legion','Zoltan & Gabor','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_064.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_064_premium.gif','enUS','Battlecry: Deal 1 damage to ALL other characters.','Battlecry','Demon',NULL,'Unlocked at Level 23.','Unlocked at Level 10.');
INSERT INTO minions VALUES ('CS2_162',157,'Lord of the Arena','Basic','Minion','Alliance','Free',6,6,5,'He used to be a 2100+ rated arena player, but that was years ago and nobody can get him to shut up about it.','E.M. Gist','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_162.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_162_premium.gif','enUS','Taunt','Taunt',NULL,NULL,'Unlocked at Priest Level 59.',NULL);
INSERT INTO minions VALUES ('CS2_213',445,'Reckless Rocketeer','Basic','Minion','Horde','Free',6,5,2,'One Insane Rocketeer. One Rocket full of Explosives. Infinite Fun.','John Polidora','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_213.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_213_premium.gif','enUS','Charge','Charge',NULL,NULL,'Unlocked at Shaman Level 59.',NULL);
INSERT INTO minions VALUES ('CS2_201',1687,'Core Hound','Basic','Minion',NULL,'Free',7,9,5,'You don’t tame a Core Hound. You just train it to eat someone else before it eats you.','E.M. Gist','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_201.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_201_premium.gif','enUS',NULL,NULL,'Beast',NULL,'Unlocked at Hunter Level 51.',NULL);
INSERT INTO minions VALUES ('CS2_088',1068,'Guardian of Kings','Basic','Minion','Neutral','Free',7,5,6,'Holy beings from the beyond are so cliché!','E.M. Gist','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_088.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_088_premium.gif','enUS','Battlecry: Restore 6 Health to your hero.','Battlecry',NULL,NULL,'Unlocked at Level 47.','Unlocked at Level 8.');
INSERT INTO minions VALUES ('CS2_222',753,'Stormwind Champion','Basic','Minion','Alliance','Free',7,6,6,'When Deathwing assaulted the capital, this soldier was the only member of his squad to survive. Now he''s all bitter and stuff.','Doug Alexander','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_222.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_222_premium.gif','enUS','Your other minions have +1/+1.','Aura',NULL,NULL,'Unlocked at Paladin Level 59.',NULL);
INSERT INTO minions VALUES ('CS2_186',712,'War Golem','Basic','Minion','Neutral','Free',7,7,7,'Golems are not afraid, but for some reason they still run when you cast Fear on them. Instinct, maybe? A desire to blend in?','Dave Kendall','True','Neutral','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_186.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_186_premium.gif','enUS',NULL,NULL,NULL,NULL,'Unlocked at Rogue Level 51.',NULL);
