CREATE TABLE spells (
    `list_cardId` VARCHAR(8) CHARACTER SET utf8,
    `list_dbfId` INT,
    `list_name` VARCHAR(18) CHARACTER SET utf8,
    `list_cardSet` VARCHAR(7) CHARACTER SET utf8,
    `list_type` VARCHAR(5) CHARACTER SET utf8,
    `list_rarity` VARCHAR(6) CHARACTER SET utf8,
    `list_cost` INT,
    `list_text` VARCHAR(76) CHARACTER SET utf8,
    `list_flavor` VARCHAR(174) CHARACTER SET utf8,
    `list_artist` VARCHAR(22) CHARACTER SET utf8,
    `list_collectible` VARCHAR(4) CHARACTER SET utf8,
    `list_playerClass` VARCHAR(7) CHARACTER SET utf8,
    `list_img` VARCHAR(73) CHARACTER SET utf8,
    `list_imgGold` VARCHAR(89) CHARACTER SET utf8,
    `list_locale` VARCHAR(4) CHARACTER SET utf8,
    `list_faction` VARCHAR(7) CHARACTER SET utf8,
    `list_mechanics_name` VARCHAR(20) CHARACTER SET utf8,
    `list_howToGet` VARCHAR(21) CHARACTER SET utf8,
    `list_howToGetGold` VARCHAR(21) CHARACTER SET utf8
);
INSERT INTO spells VALUES ('EX1_621',1362,'Circle of Healing','Classic','Spell','Common',0,'Restore #4 Health to ALL_minions.','It isn''t really a circle.','Daarken','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_621.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_621_premium.gif','enUS',NULL,NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_607',22,'Inner Rage','Classic','Spell','Common',0,'Deal $1 damage to a minion and give it +2_Attack.','They''re only smiling on the outside.','Slawomir Maniak','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_607.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_607_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_332',1189,'Silence','Classic','Spell','Common',0,'Silence a minion.','Reserved for enemy spellcasters, evil liches from beyond the grave, and karaoke nights at the Grim Guzzler.','Zoltan & Gabor','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_332.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_332_premium.gif','enUS','Neutral','Silence',NULL,NULL);
INSERT INTO spells VALUES ('EX1_014t',1694,'Bananas','Classic','Spell',NULL,1,'Give a minion +1/+1.',NULL,NULL,NULL,'Neutral','http://wow.zamimg.com/images/hearthstone/cards/enus/original/EX1_014t.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/EX1_014t_premium.gif','enUS',NULL,NULL,NULL,NULL);
INSERT INTO spells VALUES ('CS1_129',376,'Inner Fire','Classic','Spell','Common',1,'Change a minion''s Attack to be equal to its Health.','Good idea: Buffing your minions. Bad idea: Starting a conversation in the Barrens.','Steve Prescott','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS1_129.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS1_129_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_410',546,'Shield Slam','Classic','Spell','Epic',1,'Deal 1 damage to a minion for each Armor you have.','"What is a better weapon? The sharp one your enemies expect, or the blunt one they ignore?" - The Art of Warrior, Chapter 9','Raymond Swanland','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_410.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_410_premium.gif','enUS','Neutral','AffectedBySpellPower',NULL,NULL);
INSERT INTO spells VALUES ('EX1_392',400,'Battle Rage','Classic','Spell','Common',2,'Draw a card for each damaged friendly character.','"You won''t like me when I''m angry."','Alex Horley Orlandelli','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_392.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_392_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_619',756,'Equality','Classic','Spell','Rare',2,'Change the Health of ALL minions to 1.','We are all special unique snowflakes... with 1 Health.','Michal Ivan','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_619.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_619_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('CS2_104',1108,'Rampage','Classic','Spell','Common',2,'Give a damaged minion +3/+3.','Minion get ANGRY. Minion SMASH!','Jonboy Meyers','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_104.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_104_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_617',1093,'Deadly Shot','Classic','Spell','Common',3,'Destroy a random enemy minion.','Accuracy is not a highly valued trait among the mok''nathal. Deadliness is near the top, though.','Steve Prescott','True','Hunter','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_617.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_617_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_349',679,'Divine Favor','Classic','Spell','Rare',3,'Draw cards until you have as many in hand as your opponent.','This is not just a favor, but a divine one, like helping someone move a couch with a fold out bed!','Lucas Graciano','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_349.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_349_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_317',860,'Sense Demons','Classic','Spell','Common',3,'Draw 2 Demons\nfrom your deck.','Generally demons are pretty obvious and you don’t need a spell to sense them.','Raven Mimura','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_317.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_317_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_626',1366,'Mass Dispel','Classic','Spell','Rare',4,'Silence all enemy minions. Draw a card.','It dispels buffs, powers, hopes, and dreams.','Sean O''Daniels','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_626.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_626_premium.gif','enUS',NULL,'Silence',NULL,NULL);
INSERT INTO spells VALUES ('EX1_303',147,'Shadowflame','Classic','Spell','Rare',4,'Destroy a friendly minion and deal its Attack damage to all enemy minions.','Start with a powerful minion and stir in Shadowflame and you have a good time!','Dave Kendall','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_303.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_303_premium.gif','enUS','Neutral','AffectedBySpellPower',NULL,NULL);
INSERT INTO spells VALUES ('EX1_355',1522,'Blessed Champion','Classic','Spell','Rare',5,'Double a minion''s Attack.','This card causes double the trouble AND double the fun.','Tyler Walpole','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_355.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_355_premium.gif','enUS',NULL,NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_407',75,'Brawl','Classic','Spell','Epic',5,'Destroy all minions except one. (chosen randomly)','Do you know the first rule of Brawl Club?','Wayne Reynolds','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_407.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_407_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_537',394,'Explosive Shot','Classic','Spell','Rare',5,'Deal $5 damage to a minion and $2 damage to adjacent ones.','Pull the pin, count to 5, then shoot. Then duck.','Tom Baxa','True','Hunter','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_537.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_537_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_365',435,'Holy Wrath','Classic','Spell','Rare',5,'Draw a card and deal_damage equal to_its Cost.','C''mon Molten Giant!!','Justin Sweet','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_365.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_365_premium.gif','enUS','Neutral','AffectedBySpellPower',NULL,NULL);
INSERT INTO spells VALUES ('EX1_384',1174,'Avenging Wrath','Classic','Spell','Epic',6,'Deal $8 damage randomly split among all enemies.','Wham! Wham! Wham! Wham! Wham! Wham! Wham! Wham!','Alex Garner','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_384.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_384_premium.gif','enUS','Neutral','ImmuneToSpellpower',NULL,NULL);
INSERT INTO spells VALUES ('EX1_624',1365,'Holy Fire','Classic','Spell','Rare',6,'Deal $5 damage. Restore #5 Health to your hero.','Often followed by Holy Smokes!','Miguel Coimbra','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_624.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_624_premium.gif','enUS',NULL,NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_309',1100,'Siphon Soul','Classic','Spell','Rare',6,'Destroy a minion. Restore #3 Health to_your hero.','You probably should avoid siphoning your own soul. You might create some kind of weird infinite loop.','Tyler Walpole','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_309.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_309_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_354',594,'Lay on Hands','Classic','Spell','Epic',8,'Restore #8 Health. Draw_3 cards.','A grammatically awkward life saver.','Raymond Swanland','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_354.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_354_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_312',859,'Twisting Nether','Classic','Spell','Epic',8,'Destroy all minions.','The Twisting Nether is a formless place of magic and illusion and destroyed minions.','Dave Allsop','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_312.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_312_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_279',1087,'Pyroblast','Classic','Spell','Epic',10,'Deal $10 damage.','Take the time for an evil laugh after you draw this card.','Luca Zontini','True','Mage','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_279.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_279_premium.gif','enUS','Neutral',NULL,NULL,NULL);
INSERT INTO spells VALUES ('NEW1_003',163,'Sacrificial Pact','Basic','Spell','Free',0,'Destroy a Demon. Restore #5 Health to your hero.','This is the reason that Demons never really become friends with Warlocks.','Jim Nelson','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/NEW1_003.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/NEW1_003_premium.gif','enUS',NULL,NULL,'Unlocked at Level 8.','Unlocked at Level 15.');
INSERT INTO spells VALUES ('GAME_005',1746,'The Coin','Basic','Spell',NULL,0,'Gain 1 Mana Crystal this turn only.',NULL,NULL,NULL,'Neutral','http://wow.zamimg.com/images/hearthstone/cards/enus/original/GAME_005.png','http://wow.zamimg.com/images/hearthstone/cards/enus/animated/GAME_005_premium.gif','enUS',NULL,NULL,NULL,NULL);
INSERT INTO spells VALUES ('EX1_277',564,'Arcane Missiles','Basic','Spell','Free',1,'Deal $3 damage randomly split among all enemies.','You''d think you''d be able to control your missiles a little better since you''re a powerful mage and all.','Warren Mahy','True','Mage','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_277.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_277_premium.gif','enUS','Neutral','ImmuneToSpellpower','Unlocked at Level 1.','Unlocked at Level 32.');
INSERT INTO spells VALUES ('DS1_185',877,'Arcane Shot','Basic','Spell','Free',1,'Deal $2 damage.','Magi conjured arcane arrows to sell to hunters, until hunters learned just enough magic to do it themselves. The resulting loss of jobs sent Stormwind into a minor recession.','Luca Zontini','True','Hunter','http://media.services.zam.com/v1/media/byName/hs/cards/enus/DS1_185.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/DS1_185_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 32.');
INSERT INTO spells VALUES ('CS2_087',70,'Blessing of Might','Basic','Spell','Free',1,'Give a minion +3_Attack.','"As in, you MIGHT want to get out of my way." - Toad Mackle, recently buffed.','Zoltan Boros','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_087.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_087_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 45.');
INSERT INTO spells VALUES ('EX1_371',727,'Hand of Protection','Basic','Spell','Free',1,'Give a minion Divine Shield.','This spell has been renamed so many times, even paladins don’t know what it should be called anymore.','Clint Langley','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_371.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_371_premium.gif','enUS','Neutral','Divine Shield','Unlocked at Level 1.','Unlocked at Level 23.');
INSERT INTO spells VALUES ('CS1_130',279,'Holy Smite','Basic','Spell','Free',1,'Deal $2 damage.','It doesn''t matter how pious you are. Everyone needs a good smiting now and again.','Steve Ellis','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS1_130.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS1_130_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 23.');
INSERT INTO spells VALUES ('EX1_360',854,'Humility','Basic','Spell','Free',1,'Change a minion''s Attack to 1.','This card makes something really damp. Oh wait. That''s "Humidity."','Daren Bader','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_360.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_360_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 6.','Unlocked at Level 28.');
INSERT INTO spells VALUES ('CS2_084',141,'Hunter''s Mark','Basic','Spell','Free',1,'Change a minion''s Health to 1.','Never play ''Hide and Go Seek'' with a Hunter.','Jimmy Lo','True','Hunter','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_084.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_084_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 6.','Unlocked at Level 40.');
INSERT INTO spells VALUES ('CS2_004',613,'Power Word: Shield','Basic','Spell','Free',1,'Give a minion +2_Health.\nDraw a card.','Sure the extra protection is nice, but the shield really reduces visibility.','Jessica Jung','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_004.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_004_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 47.');
INSERT INTO spells VALUES ('EX1_400',636,'Whirlwind','Basic','Spell','Free',1,'Deal $1 damage to ALL_minions.','The way to tell seasoned warriors from novice ones: the novices yell "wheeeee" while whirlwinding.','Jonboy Meyers','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_400.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_400_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 6.','Unlocked at Level 32.');
INSERT INTO spells VALUES ('CS2_025',447,'Arcane Explosion','Basic','Spell','Free',2,'Deal $1 damage to all enemy minions.','This spell is much better than Arcane Implosion.','Howard Lyon','True','Mage','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_025.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_025_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 28.');
INSERT INTO spells VALUES ('CS2_114',940,'Cleave','Basic','Spell','Free',2,'[x]Deal $2 damage to\ntwo random enemy\nminions.','Hey you two…could you stand next to each other for a second…','Phroilan Gardner','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_114.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_114_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 2.','Unlocked at Level 40.');
INSERT INTO spells VALUES ('CS2_236',1361,'Divine Spirit','Basic','Spell','Free',2,'Double a minion''s Health.','Double the trouble. Double the fun!','Jim Pavelec','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_236.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_236_premium.gif','enUS',NULL,NULL,'Unlocked at Level 2.','Unlocked at Level 28.');
INSERT INTO spells VALUES ('CS2_108',785,'Execute','Basic','Spell','Free',2,'Destroy a damaged enemy minion.','It''s okay, he deserved it.','Dany Orizio','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_108.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_108_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 47.');
INSERT INTO spells VALUES ('CS2_105',1007,'Heroic Strike','Basic','Spell','Free',2,'Give your hero +4_Attack this turn.','Really, if you''re a hero, this is every strike.','Jonboy Meyers','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_105.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_105_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 15.');
INSERT INTO spells VALUES ('CS2_089',291,'Holy Light','Basic','Spell','Free',2,'Restore #6 Health.','If you are often bathed in Holy Light, you should consider wearing sunscreen.','Zoltan & Gabor','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_089.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_089_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 15.');
INSERT INTO spells VALUES ('DS1_233',545,'Mind Blast','Basic','Spell','Free',2,'Deal $5 damage to the enemy hero.','This spell blasts you directly in the MIND.','Dave Allsop','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/DS1_233.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/DS1_233_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 15.');
INSERT INTO spells VALUES ('CS2_234',1367,'Shadow Word: Pain','Basic','Spell','Free',2,'Destroy a minion with 3_or less Attack.','A step up from a spell cast by many beginning acolytes: "Shadow Word: Annoy".','Raymond Swanland','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_234.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_234_premium.gif','enUS',NULL,NULL,'Unlocked at Level 1.','Unlocked at Level 36.');
INSERT INTO spells VALUES ('CS2_023',555,'Arcane Intellect','Basic','Spell','Free',3,'Draw 2 cards.','Playing this card makes you SMARTER. And let''s face it: we could all stand to be a little smarter.','Dave Berggren','True','Mage','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_023.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_023_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 15.');
INSERT INTO spells VALUES ('CS2_061',919,'Drain Life','Basic','Spell','Free',3,'Deal $2 damage. Restore #2 Health to your hero.','"I''ve just sucked one year of your life away."','Alex Horley Orlandelli','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_061.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_061_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 45.');
INSERT INTO spells VALUES ('CS2_057',914,'Shadow Bolt','Basic','Spell','Free',3,'Deal $4 damage\nto a minion.','It’s a Bolt. It''s made out of Shadow. What more do you need to know!','Dave Allsop','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_057.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_057_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 47.');
INSERT INTO spells VALUES ('EX1_622',1363,'Shadow Word: Death','Basic','Spell','Free',3,'Destroy a minion with 5_or more Attack.','If you miss, it leaves a lightning-bolt-shaped scar on your target.','Raymond Swanland','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_622.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_622_premium.gif','enUS',NULL,NULL,'Unlocked at Level 8.','Unlocked at Level 43.');
INSERT INTO spells VALUES ('EX1_606',1023,'Shield Block','Basic','Spell','Free',3,'Gain 5 Armor.\nDraw a card.','Shields were invented because Face Block is USELESS.','Michael Komarck','True','Warrior','http://media.services.zam.com/v1/media/byName/hs/cards/enus/EX1_606.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/EX1_606_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 8.','Unlocked at Level 28.');
INSERT INTO spells VALUES ('CS2_092',943,'Blessing of Kings','Basic','Spell','Free',4,'Give a minion +4/+4. (+4 Attack/+4 Health)','Given the number of kings who have been assassinated, are you sure you want their blessing?','Lucas Graciano','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_092.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_092_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 10.','Unlocked at Level 49.');
INSERT INTO spells VALUES ('CS2_093',476,'Consecration','Basic','Spell','Free',4,'Deal $2 damage to all_enemies.','Consecrated ground glows with Holy energy. But it smells a little, too.','Vance Kovacs','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_093.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_093_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 4.','Unlocked at Level 43.');
INSERT INTO spells VALUES ('CS2_029',315,'Fireball','Basic','Spell','Free',4,'Deal $6 damage.','This spell is useful for burning things. If you''re looking for spells that toast things, or just warm them a little, you''re in the wrong place.','Ralph Horsley','True','Mage','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_029.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_029_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 44.');
INSERT INTO spells VALUES ('CS2_094',250,'Hammer of Wrath','Basic','Spell','Free',4,'Deal $3 damage.\nDraw a card.','A good paladin has many tools. Hammer of Wrath, Pliers of Vengeance, Hacksaw of Justice, etc.','Efrem Palacios','True','Paladin','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_094.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_094_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 32.');
INSERT INTO spells VALUES ('CS2_062',950,'Hellfire','Basic','Spell','Free',4,'Deal $3 damage to ALL_characters.','It''s spells like these that make it hard for Warlocks to get decent help.','Chippy','True','Warlock','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_062.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_062_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 49.');
INSERT INTO spells VALUES ('DS1_183',292,'Multi-Shot','Basic','Spell','Free',4,'Deal $3 damage to two random enemy minions.','You see, it''s all about throughput.','Benjamin Zhang','True','Hunter','http://media.services.zam.com/v1/media/byName/hs/cards/enus/DS1_183.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/DS1_183_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 36.');
INSERT INTO spells VALUES ('CS2_022',77,'Polymorph','Basic','Spell','Free',4,'Transform a minion\ninto a 1/1 Sheep.','There was going to be a pun in this flavor text, but it just came out baa-d.','Vance Kovacs','True','Mage','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_022.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_022_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 1.','Unlocked at Level 47.');
INSERT INTO spells VALUES ('CS1_112',841,'Holy Nova','Basic','Spell','Free',5,'Deal $2 damage to all enemies. Restore #2_Health to all friendly characters.','If the Holy Light forsakes you, good luck casting this spell. Also, you''re probably a jerk.','Luca Zontini','True','Priest','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS1_112.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS1_112_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 6.','Unlocked at Level 45.');
INSERT INTO spells VALUES ('CS2_032',1004,'Flamestrike','Basic','Spell','Free',7,'Deal $4 damage to all enemy minions.','When the ground is on fire, you should not stop, drop, and roll.','Romain De Santi','True','Mage','http://media.services.zam.com/v1/media/byName/hs/cards/enus/CS2_032.png','http://media.services.zam.com/v1/media/byName/hs/cards/enus/animated/CS2_032_premium.gif','enUS','Neutral',NULL,'Unlocked at Level 10.','Unlocked at Level 51.');
